### ISSUE TITLE
[FR] collapsing/expanding groups

### ISSUE THREAD

**Issue by PennHui666** [Developer-Mike/obsidian-advanced-canvas#10]
## Issue Summary
In the current project, Canvas serves as a core component offering robust graphic rendering and organization capabilities. However, when dealing with complex visual scenarios or large-scale projects, the lack of expand/collapse functionality for Group elements can lead to user frustration and reduced efficiency in viewing or editing multi-level content.

### Current State
I have investigated multiple similar projects to find a solution, but unfortunately, the current products on the plugin market and GitHub do not provide an intuitive and efficient Group folding/expanding implementation.
Your project is excellent at enhancing the canvas experience, so I'd love to get some help here.

### Proposed Improvement
- Add controls to group style UI.

When the control is clicked, the group shrinks to show only the title. Click again and the group will expand to show all contents.

A good concrete example is the way group elements are handled in Marginnote3, where this functionality is achieved by clicking the expand (⊕) or collapse (⊖) symbols next to the group node.
![Marginnote3 example](https://github.com/Developer-Mike/obsidian-advanced-canvas/assets/72249772/323ae4c7-3eac-4291-be84-9e13118e82e2)

### Possible Alternatives
- In the mini-toolbar above a group, put a collapse/uncollapse control.
![Menu Control](https://github.com/Developer-Mike/obsidian-advanced-canvas/assets/72249772/f9feb9a9-c354-4c36-af2f-66b0f48935fb)

## Possible impact
When implementing this feature, you need to consider its impact on UI design, performance optimization, and DOM tree operation and rendering efficiency, so this is just a feature suggestion, not a "do it now" demand.

## Additional Information
Here is a project that has been put on the shelves for reference：[Obsidian Collapse Node](https://github.com/quorafind/obsidian-collapse-node)
The project in the above link extends the concept of folding and unfolding to the canvas node, but the overall implementation effect is not good. I think it's enough to implement it only at the group level.

**Comment by Developer-Mike** [comment]
Thank you for your detailed feature request 🙏🏻. This is definitely a feature that I want to implement! But instead of adding a popup menu option, I would prefer a button next to the group name (Like the ⊕/⊖ icons from Marginnote3). Because if you add a popup menu option, you have to do two clicks to expand/collapse a group. Additionally, it would "clutter" the popup menu. Do you agree with my arguments?

**Comment by PennHui666** [comment]
> Thank you for your detailed feature request 🙏🏻. This is definitely a feature that I want to implement! But instead of adding a popup menu option, I would prefer a button next to the group name (Like the ⊕/⊖ icons from Marginnote3). Because if you add a popup menu option, you have to do two clicks to expand/collapse a group. Additionally, it would "clutter" the popup menu. Do you agree with my arguments?

I totally agree, just do it the way you want to implement it. Also, I would like to make one more suggestion about this. Can the content of a group element be loaded when it is expanded and discarded when it is collapsed? I think this can optimize performance when opening and using large canvas files.

**Comment by codyburleson** [comment]
I second this request!!! However, why does this have to be only for groups? Any node with children should be collapsible/expandable. A lot of the mind-mapping tools do it this way, for example, without a concept of groups.

**Comment by Developer-Mike** [comment]
> I totally agree, just do it the way you want to implement it. Also, I would like to make one more suggestion about this. Can the content of a group element be loaded when it is expanded and discarded when it is collapsed? I think this can optimize performance when opening and using large canvas files.

I think loading and unloading would be overkill (and hard to implement). If you want to unload the content, you can use a portal.

**Comment by Developer-Mike** [comment]
> I second this request!!! However, why does this have to be only for groups? Any node with children should be collapsible/expandable. A lot of the mind-mapping tools do it this way, for example, without a concept of groups.

Do you mean that all outgoing edges of a node should collapse if you collapse a node?

**Comment by codyburleson** [comment]
> Do you mean that all outgoing edges of a node should collapse if you collapse a node?
 
 The outgoing edges and child nodes should disappear. Something kind of like this, although you need a way to visually indicate that a node has children, after it is collapsed. Maybe the twisty control stay visible when a node has children and is collapsed, but it does not have to be visible when the node is expanded unless you hover over the control point.
 
![obsidian-canvas-collapsable-nodes](https://github.com/Developer-Mike/obsidian-advanced-canvas/assets/7317733/3ab76fec-d0dc-41fe-870b-e3f332a98102)

**Comment by Developer-Mike** [comment]
> If a big blank space is left open, then it may be kind of a moot point

Yes. This feature would need to be added to make it useful. But first, I'll implement the group collapse.

**Comment by PennHui666** [comment]
`codyburleson` wrote:
> Any node with children should be collapsible/expandable.

I'm very grateful to `codyburleso` for sharing this perspective, but I have a different opinion.

I don't feel like every node should be collapsible/expandable.Because the connections between some nodes are bidirectional, the parent-child relationship cannot be determined. And some nodes exist as free nodes and do not need this function.

My suggestion for this is to add an option to the right-click menu of the selected node to give the node mind map capabilities, so that you can add child nodes or sibling nodes through the Tab and Enter keys, and you can also collapse the child nodes.

As for more detailed functional performance, I think it might as well open a new issue to discuss it.

**Comment by Developer-Mike** [comment]
FYI: There is a feature freeze until the next code review of the Obsidian team.

**Comment by Developer-Mike** [comment]
Current state: This feature is harder than initially thought and will take some time to fully implement. You really need to unload the nested nodes for the canvas to work correctly.

**Comment by PennHui666** [comment]
@Developer-Mike 

> Current state: This feature is harder than initially thought and will take some time to fully implement. You really need to unload the nested nodes for the canvas to work correctly.

What do you mean by nested nodes? Is a node nested within multiple groups?
btw, can I give you some sponsorship?

**Comment by Developer-Mike** [comment]
With "nested nodes" I meant nodes, that are inside a group. If you just hide them using CSS, the node snapping is still there (and other problems). And if you want to support me, I've added a [Ko-fi link](https://ko-fi.com/X8X27IA08) to the README ❤️

**Comment by Developer-Mike** [comment]
FYI: This feature was added in the new beta version (2.6.0-beta.1).

**Comment by PennHui666** [comment]
@Developer-Mike 
I tried this new feature and it was a great experience.
Are there any plans to apply this feature to mind map style node connections in the future?
Just like below
![exam](https://github.com/Developer-Mike/obsidian-advanced-canvas/assets/72249772/83d9a6df-6bc7-4c8c-89bf-509b4abd6f66)

**Comment by Developer-Mike** [comment]
This would require something like a "Mind map Mode" to be useful. I don't know if or when this will be added. Please create a new feature request to keep this issue's original topic.

**Comment by Developer-Mike** [comment]
This feature is now in the latest release (2.6.0)
