### ISSUE TITLE
Add a way for new paths to be nondirectional

### ISSUE THREAD

**Issue by kilmameri** [Developer-Mike/obsidian-advanced-canvas#101]
I'd like my paths to be created non-directional. There have been a few feature requests for obsidian itself, but they're a few years old. I couldn't find a workaround

This could be implemented by adding a new "arrow style", one that is invisible

(im new to github, sorry if this is the wrong place. advice in solving my issue would also be appreciated)

**Comment by Developer-Mike** [comment]
Thank you for your feature request. This behavior can be (rather easily) implemented in the default edge styles config. I currently don't have much free time tho. So don't expect it to get implemented before December.

**Comment by Developer-Mike** [comment]
This feature got implemented and will be available in the next release.
