### ISSUE TITLE
[FR] When exiting presentation mode: update canvas viewport to center on presented node

### ISSUE THREAD

**Issue by amitnovick** [Developer-Mike/obsidian-advanced-canvas#105]
Hello, @Developer-Mike,

This is a wonderful plugin and I greatly appreciate your work on it!

## Problem
I start a presentation, and at some point press Esc to make some changes to a slide
However when I exit the presentation, the viewport is back where it was before I entered presentation mode (so I have to look for the node I was viewing)

## Solution
When in presentation mode, upon pressing Esc, center the canvas viewport with the last viewed node in the center

---
Is something like this possible?
What is the difficulty?

Thanks
Amit

**Comment by Developer-Mike** [comment]
Thank you for sharing your suggestion. The viewport gets restored on purpose after the presentation is exited. This can easily be changed to an optional setting.

**Comment by Developer-Mike** [comment]
I don't know which behaviour will be the default one yet 🤔...
