### ISSUE TITLE
Trailing commas

### ISSUE THREAD

**Issue by Viinnnn** [Developer-Mike/obsidian-advanced-canvas#109]
There might be an issue after reformating, where trailing commas are being set by accident. See {"height":640,}
I recently deactivated the plugin and after that the files I opened while having the plugin enabled where corrupted, because the files have been formated with the trailing comma. My guess is that the deactivation process deletes a property, but doesn't account for it being the last item and possible leaving a trailing comma behind.

![Bild_2024-10-03_232608178](https://github.com/user-attachments/assets/15a8e2af-8708-47d5-b9d5-a4386f3335ba)

**Comment by Developer-Mike** [comment]
This is an Obsidian issue (#82).
