### ISSUE TITLE
"Drag to add slide" bug

### ISSUE THREAD

**Issue by Marco-Mindstone** [Developer-Mike/obsidian-advanced-canvas#11]
Hi,

when I utilize the "Drag to Slide" button, my nodes vanish and no slide gets created. Is this supposed to be operational or is it still considered "work in progress"?

Thanks

**Comment by Developer-Mike** [comment]
The "Drag to add Slide" menu option should be functional... Can you please check if you have set the slide ratio in the settings? I did have a similar issue caused by the setting that wasn't set. I totally forgot to fix the default value for this setting 🫣😅

**Comment by Marco-Mindstone** [comment]
Perfect, that was the problem. Thank you Mike.
You're doing a great job with the plugin. Keep it up!
