### ISSUE TITLE
[FR] Functionality to add custom default colors to the Node color picker

### ISSUE THREAD

**Issue by paranoiks** [Developer-Mike/obsidian-advanced-canvas#12]
When choosing a color for a Node there are currently only six options. If i want to use a custom color I have to pick it every time. I would like to be able to add custom colors to choose from

**Comment by paranoiks** [comment]
It works! Thanks a lot

**Comment by vkhatuntsevv** [comment]
hi, there's another issue with this. if you add more than 7 colors, color picker won't show you which color you chose (as it does for the first 6 ones)
![image](https://github.com/Developer-Mike/obsidian-advanced-canvas/assets/161768359/d0c0f8cf-e55f-4d39-a465-9d4e6d234e63)
![image](https://github.com/Developer-Mike/obsidian-advanced-canvas/assets/161768359/af5f4966-2413-4efb-8b18-cac6f3c9d547)
as you can see on the 2nd pic, it does not show any color chosen, whereas it's the 2nd one from the end, excluding custom color picker. how do i resolve this?

**Comment by Developer-Mike** [comment]
Will be fixed in the 2.5.2 update 👍🏻
