### ISSUE TITLE
Added custom colors are all grey

### ISSUE THREAD

**Issue by 5yF0Rc3** [Developer-Mike/obsidian-advanced-canvas#126]
Adding this 
``` 
:root {
  --canvas-color-7: 150, 24, 24;
  --canvas-color-8: 200, 130, 130;
  --canvas-color-9: 150, 205, 170;
}
``` 

will result in only grey Colors. What I am missing?
![grafik](https://github.com/user-attachments/assets/606d3d02-ca08-4e17-963f-330713979116)

Obsidian Version: 1.7.7

**Comment by Developer-Mike** [comment]
That's strange. It works on my computer 😅.
Which theme are you using?

And if you are using Advanced Canvas on a PC, it would be helpful if you could open the developer tools (Ctrl+Shift+I) and run this command and report the result: `document.getElementById("mod-custom-colors").innerText`

**Comment by 5yF0Rc3** [comment]
It's the theme! Im using Everforest.
The result on Everforest is: ''
And with the basic theme - which works: 
```
'\n      .mod-canvas-color-7 {\n        --canvas-color: var(--canvas-color-7);\n      }\n    \n      .mod-canvas-color-8 {\n        --canvas-color: var(--canvas-color-8);\n      }\n    \n      .mod-canvas-color-9 {\n        --canvas-color: var(--canvas-color-9);\n      }\n    '
```

**Comment by Developer-Mike** [comment]
Thanks for the quick reply (and the edit 😄). I'll close this issue now, but you can always open it again and ask for compatibility with a certain theme.

**Comment by 5yF0Rc3** [comment]
It's very strange. I have to reassign the theme everytime I start Obsidian, else it won't work...
