### ISSUE TITLE
In some cases, the node will not automatically adjust its height

### ISSUE THREAD

**Issue by oceanst1** [Developer-Mike/obsidian-advanced-canvas#128]
When the input content is too long, which causes the content of the node to wrap automatically, the first few English letters (including numbers or Chinese characters) input in a new line will not make the node automatically adjust its height.
![1733899135155](https://github.com/user-attachments/assets/70f593d1-9d5d-41f3-902e-e71e51610040)

**Comment by oceanst1** [comment]
I found that this problem will not appear until the "Snap to grid" option is turned on.

**Comment by Developer-Mike** [comment]
Thank you for reporting this. This issue will be fixed in the next update.
