### ISSUE TITLE
Adv-Canvas Crashes when cutting off the path of a line in "map" mode.

### ISSUE THREAD

**Issue by Kamida5192** [Developer-Mike/obsidian-advanced-canvas#129]
Steps to replicate:

1. Put down two notes in canvas and connect them with a line. Select the line to be the "Map" option
2. Make 4 other notes and arrange them in a way where one of the boxes is enclosed within the 4 notes.
3. Obsidian will hang as the connecting line is unable to path find to its destination

Platform: Mac OS Sequoia 15.1.1
Obsidian 1.7.7
Advanced Canvas Version: 3.2.0

<img width="817" alt="image" src="https://github.com/user-attachments/assets/45d414d0-b2d1-4397-ab76-f48a3bcbc6ef" />

**Comment by Developer-Mike** [comment]
Thank you for creating the issue. It will be fixed in the next version.

**Comment by Kamida5192** [comment]
Hey Developer Mike,

I just remembered I never said "Thank you" for addressing this. So Thank you for addressing this. I saw #132 and I'm sorry that you have to deal with those types of people. Please enjoy the Kofi as I love advanced canvas. 

Thank you,
Cameron

**Comment by Developer-Mike** [comment]
@Kamida5192 Thank you so much for the donation 🙏🏼. Bug reports like yours help to tackle the less well-explained bugs like the one you've referred to 😉
