### ISSUE TITLE
[FR] Add lines at any position on the card

### ISSUE THREAD

**Issue by wwjCMP** [Developer-Mike/obsidian-advanced-canvas#13]
Is it possible to add connections anywhere on a card, rather than just at the four edges?

**Comment by Developer-Mike** [comment]
I think this will be really difficult to implement, but I'll take a look if this feature could be added.

**Comment by Pixel3ro** [comment]
> I think this will be really difficult to implement, but I'll take a look if this feature could be added.

@wwjCMP  without knowing about your usecase, your request sound's like a visual enhancement. 
I am requesting a Convenience enhancement in #23 . If you think we are looking ways to solve the same solution, maybe there is one more way to solve it, hopefully an easier one. @Developer-Mike

**Comment by wwjCMP** [comment]
What I mean is 
![Snipaste_2024-03-07_09-35-03](https://github.com/Developer-Mike/obsidian-advanced-canvas/assets/32979859/77cf5130-64d5-461b-8c32-1f1fc74f8009)

**Comment by Pixel3ro** [comment]
Gotcha. we are talking about different things here

**Comment by Developer-Mike** [comment]
Closing this issue because #37 is similar and more likely to be implemented.
