### ISSUE TITLE
[CRASH] Prevent crash when (accidentally) using recursive portals

### ISSUE THREAD

**Issue by CodeAndWeb** [Developer-Mike/obsidian-advanced-canvas#130]
Create a.canvas, b.canvas, c.canvas

a.canvas: open a portal to b.canvas
b.canvas: open a portal to a.canvas

Direct recursion is handled properly but indirect is not:

c.canvas: open a portal to a.canvas => Boom!

**Comment by Developer-Mike** [comment]
Missed that! Thank you for the report. It will be fixed in the next update.
