### ISSUE TITLE
[iPad + Obsidian Synced Vault] “Auto-resize node” feature causes note to exponentially increase in height with each new character typed

### ISSUE THREAD

**Issue by 6xolotl** [Developer-Mike/obsidian-advanced-canvas#131]
No idea what the root of the problem could be.

![IMG_2522](https://github.com/user-attachments/assets/5ee0b02b-1dca-4eb0-9e96-87b76968280a)

Other plugins installed (just in case one of them is a known conflict I’m unaware of):

- Audio Player
- AutoPause
- CSS Editor
- File Color
- File Info Panel
- Highlightr
- Lite Gallery
- Minimal Theme Settings
- Novel word count
- Reset Font Size
- Smart Typography
- Style Settings
- Tag Wrangler
- Tags Overview
- Templater
- Word Sprint
- Wrap with shortcuts

**Comment by Developer-Mike** [comment]
Can you please check if it also happens without a synced vault and without any plugins (except AC of course). Thanks 😊

**Comment by Developer-Mike** [comment]
I was able to reproduce this bug. I'll try to resolve it asap.

**Comment by Developer-Mike** [comment]
It got fixed in `3.3.0`
