### ISSUE TITLE
[FR] Ability to Edit Canvas Card Menu

### ISSUE THREAD

**Issue by Pixel3ro** [Developer-Mike/obsidian-advanced-canvas#14]
The ability to Disable the "Create groups independently of the nodes" from the Canvas Card Menu would be helpful to clear up some space, As I don't use it at all. 
The declutter would be beneficial for other plugins such as "Canvas Daily Note Plugin"

Along with this, the ability to hide "Drag to Add note from vault", the default Canvas feature would be nice too since I don't use it either. This request would work well with my other feature request "Double-click to add Note instead of Card"

**Comment by Developer-Mike** [comment]
All node types will remain in the card menu. But you can easily hide unwanted buttons using CSS.
