### ISSUE TITLE
[FR] Double-click to add Note instead of Card

### ISSUE THREAD

**Issue by Pixel3ro** [Developer-Mike/obsidian-advanced-canvas#15]
Since I write on Canvas and link my thoughts right-there, I would prefer to create a Note with a Double-Click instead of a Card/Node. It'd be handy for heavy writers like me.

**Comment by Pixel3ro** [comment]
This Context is linked to another Feature Request, "[Ability to make Back-links with Connections/Edges](https://github.com/Developer-Mike/obsidian-advanced-canvas/issues/16)" this is a highly requested feature in the community.

If you have understood my workflow from the mentioned feature request, you'd realize I got no use for a Card since they can't make backlinks. So I primarily use Notes.

**Comment by Pixel3ro** [comment]
Cards are occasionally used as a place for links to converge into a Node(Cluster of Arrows/Edges), and sometimes I use Cards to Visually represent what the section is about, like small Headings.

**Comment by Developer-Mike** [comment]
This default behavior isn't planned to be overwritten. But I will try to add a command to create a file node so you can assign a hotkey to it. Would you appreciate this command?

**Comment by Pixel3ro** [comment]
> add a command to create a file node so you can assign a hotkey to it

Thanks for considering this. 
Definitely the Command would be of help. It's just that Double-click to add is the most convenient to create/add notes.

**Comment by Developer-Mike** [comment]
After some thinking, both features got added in the version `2.6.4`

**Comment by Pixel3ro** [comment]
thanks for adding the feature. 
there is a small issue. while i can pick existing files by "double-click-to-add", there is no option to create a new file using the same

whereas   right-click > add-note-from-vault   allows you to type a name, if the file doesnt exist, you can hit enter to create the file. i'd be nice if you could add this feature. then the feature set will be complete.

**Comment by Developer-Mike** [comment]
Didn't know that this feature existed 🫣. I'll add it in the next version.

**Comment by Pixel3ro** [comment]
> Didn't know that this feature existed 🫣. I'll add it in the next version.

thanks a lot. youre awesome

**Comment by Developer-Mike** [comment]
Fixed in version `2.6.6` 👍🏻

**Comment by Pixel3ro** [comment]
works like a charm

**Comment by Pixel3ro** [comment]
is feature #16 in the works? i'm curious

**Comment by Developer-Mike** [comment]
@Pixel3ro ATM, no. I have some IRL stuff to do and this is a bigger feature request. But it has a "high" priority 😉
