### ISSUE TITLE
[FR] Group Theming

### ISSUE THREAD

**Issue by Pixel3ro** [Developer-Mike/obsidian-advanced-canvas#17]
Since Notes are grouped, following a color theme makes the Groups look distinct from each-other, while the contents of a group are of the same color creating a sense of Harmony/Homogeneity within the Group.

In my [other feature request](https://github.com/Developer-Mike/obsidian-advanced-canvas/issues/16#issuecomment-1975652327), I had recommended avoiding the use of distinctive visual elements since that would create a hierarchy in the Canvas which may not be apt. But using colors in the Group is very appropriate due to the fore mentioned reasons.
  
The color of the Note, the color of the Group's frame, and the color of the connecting arrows. 
These can be coded to pick a Triadic color from the color wheel.

**Comment by Developer-Mike** [comment]
In my opinion, this is a feature that not many would use. You can easily theme the nested nodes by selecting everything in the group (Group = Rectangle, Selection = Rectangle → 👌🏻). This existing method gives you the freedom to select the color manually (by e.g. topic) and you can even escape this pattern for "special" nodes.
