### ISSUE TITLE
[FR] Fixed Slide Ratio + Wrap selection into the slide

### ISSUE THREAD

**Issue by Pixel3ro** [Developer-Mike/obsidian-advanced-canvas#19]
As the title says
1. The Slide ratio can be easily changed upon dragging the corners. I would like to change the Scale, while retaining the ratio. Setting a fixed ratio such as 16:9 should be followed. 

2. My workflow is having a completed Canvas and sorting out the Slides at the end. But this feature forces me to rearrange the Canvas which I don't like. Sometimes the notes get stuck to the Frame and trying to move the Frame drags my notes around too. 
To fix this, the ability to select multiple notes, and then creating a Slide-Group around it in the set ratio(16:9) would be nice. 

3. Also, I don't really use the Slide icon in the Canvas Card menu. Even if I did use it, its a rarely used feature by nature. I don't want to keep it in the Canvas Card menu. The toggle to disable/hide that would help me free up the space and make my screen look mimimal/distraction free.

**Comment by Developer-Mike** [comment]
1, 2. Will be added 👍🏻 
3. Is the same as #14 → I'll answer there

**Comment by Developer-Mike** [comment]
Added in version `2.6.5`
