### ISSUE TITLE
[FR] Linking Mode/Shortcut

### ISSUE THREAD

**Issue by Pixel3ro** [Developer-Mike/obsidian-advanced-canvas#23]
Right now the users are expected to click on the exact spot to make connection. in the [example use-case](https://github.com/Developer-Mike/obsidian-advanced-canvas/issues/16#issuecomment-1975554673) mentioned here, Linking is a primary task frequently performed. 
Having the ability to Hold a button while clicking an item, which acts as a shortcut to spawn Arrow will be helpful. 

Maybe having a mode where only links are formed. This could be added to [Better-Readonly](https://github.com/Developer-Mike/obsidian-advanced-canvas?tab=readme-ov-file#better-readonly) feature set, where users are expected to read and form connections.

**Comment by Developer-Mike** [comment]
Adding this feature to the "Better Readonly" isn't an option because it is and will stay "read only". Can you suggest a specific shortcut key or something similar? Because I can't think about a key combination that would make sense and wouldn't interrupt other functions.

**Comment by Pixel3ro** [comment]
Yeah. "read only" makes sense. 
I'll think about the keyboard shortcut and get back to you.

I recommend adding an icon to the Canvas Card menu, that'd help make it independent of the keyboard. I use a 2-in-1 Convertible laptop, and I prefer using Tablet mode for reading. I'm sure ipad or mobile users will also benefit from this.

**Comment by Developer-Mike** [comment]
Closed due to inactivity.
