### ISSUE TITLE
[FR] Open in Split-View shortcut (needs modification in it's behavior)

### ISSUE THREAD

**Issue by Pixel3ro** [Developer-Mike/obsidian-advanced-canvas#26]
Earlier when I made this request, you [said](https://github.com/Developer-Mike/obsidian-advanced-canvas/issues/20#issuecomment-1981513952) it may not deserve any immediate attention for now. I guessed the effort:benefit isn't significant. 
- For now I request you to make shortcuts similar to Ctrl+Alt+Click which opens the file in split-view(right). while the Canvas stays open in the left-pane.
    - The problem is, it creates a new-split-view everytime it's used. Since this is created for users who work on multiple files at the same time. But I am hoping to view/edit one file at a time, while my primary need is a larger view of the notes in my Canvas. 
    Modifying this shortcut to open-files-in-new-tabs within existing-split-pane(without creating a new split-pane) would be enough to fit my needs, for now, maybe forever. 
        - It'd be nice if this feature could be set to as default when i click on the file name(outside the note).

**Comment by Developer-Mike** [comment]
Closed due to inactivity.

**Comment by Pixel3ro** [comment]
looks like some people have been [asking](https://forum.obsidian.md/t/how-to-limit-split-view-to-just-2-panes-and-open-new-tabs-in-those-panes/61526) for this feature. i looked around and i couldn't find anything that solves this usecase. it'd be nice to open my files in the right split-pane and work on them while the left split-pane has the canvas intact. 

im not sure if this addition belongs to "advanced-canvas", or if it deserves its own plugin.
