### ISSUE TITLE
[FR] Larger Editor (Overlay)

### ISSUE THREAD

**Issue by Pixel3ro** [Developer-Mike/obsidian-advanced-canvas#27]
The following is how I originally imagined #26, which is slightly better than using split-view imo. 

When someone who writes a lot from Canvas, or reading a very long Note, The small card view may not be comfortable. 

- The ability to Zoom into the Canvas, fitting the note to ~80% of the screen. 
    - This is executed upon Triple-Clicking a Note, making a handy and intuitive key to access this feature. 
    - Upon pressing <Esc> the view zooms-out to initial value. 
    - Making it easier to form Spatial awareness in the Canvas would add to the user experience. 
        - It is important to have perceivable yet quick animation while zooming in and out. 
        - I mentioned ~80% of the screen is utilized to display the note, and not 100% because, the background - connections - files around the Note should be visible to create a sense of being in the Canvas and the Note's relative position within it. 

Another way of achieving this. 
- While zooming into the note is one way of achieving it, a lot of space in the Screen is wasted since most Notes are Square and the Screens are 16:9. 
    - A Editor Overlay animated-launched from the note upon triple-clicking it. 
    - Clicking outside the Editor Overlay should close it. OR <Esc> closes it
    - This might give the user the benefit of a fully utilizing the screen, and offering a Focus reading in-contrast to the spatial awareness in the earlier method.

**Comment by Pixel3ro** [comment]
i just found this [Hover-Editor](https://github.com/nothingislost/obsidian-hover-editor)
I will try this and update.

**Comment by Developer-Mike** [comment]
Closed due to inactivity.

**Comment by Pixel3ro** [comment]
Hover editor doesn't work in Canvas. 

and Hover editor is designed to quickly work on a backlink. even if it worked in Canvas, it'd create multiple copies of the same file leading to more clutter, and the primary issue here is about utilizing more screen-space, while Hover Editor is just another small window.
