### ISSUE TITLE
[FR] Enable Hower-to-View feature in Canvas

### ISSUE THREAD

**Issue by Pixel3ro** [Developer-Mike/obsidian-advanced-canvas#28]
This is an alternate solution to the problem cited in #26 

Obsidian already offers a Hover-to-Preview feature, by Holding Ctrl while hovering over a File-name/Backlink. 
But it doesn't work in Canvas. Enabling this feature inside Canvas solves half the problem of being able to Read. 
    - For writing, maybe the Hover-View is modified to edit the document. Or the user resorts to other ways such as opening it in Split-View, etc.

**Comment by Pixel3ro** [comment]
i just found this [Hover-Editor](https://github.com/nothingislost/obsidian-hover-editor)
I will try this and update.

**Comment by Developer-Mike** [comment]
To enable the hover preview you can add this CSS snippet:

```css
.canvas-node-content-blocker {
  display: none; /* Or pointer-events: none; */
}
```

Due to some minor issues this snippet creates, it won't be added to the plugin.

**Comment by Pixel3ro** [comment]
> both the [Hover-Editor](https://github.com/nothingislost/obsidian-hover-editor) and the CSS snippet you provided did not work from Canvas.

**Comment by Pixel3ro** [comment]
can you make Ctrl+Click open up a popup editor instead of opening a new tab. this will be super handy to work with many notes rather than having to zoom in and out. 
in that case, the whole canvas will serve the function of the _global-map_ mentioned in #61 
and editing can be comfortably done with pop-up editors. 
it feels important to me because: sometimes i set the zoom levels to a bare minimum for ease if navigation. this makes the font being too small, and i am forced to squint and focus, all for the sake of navigation which is the primary purpose of canvas.
