### ISSUE TITLE
[BUG]Collapsed groups will be collapsed together with the edges of other groups

### ISSUE THREAD

**Issue by PennHui666** [Developer-Mike/obsidian-advanced-canvas#29]
## Issue Summary
I don't know if this is a bug, but handling the positional relationship between collapsed groups is really a problem.
Please see the GIF below for specific questions.
![exam](https://github.com/Developer-Mike/obsidian-advanced-canvas/assets/72249772/413aa7af-914f-4bba-a9c6-6068d437cba4)

## Possible solutions
- Add edge detection?

**Comment by Developer-Mike** [comment]
Do you mean that the "test2" group gets collapsed inside "test 1"?

**Comment by PennHui666** [comment]
@Developer-Mike 
> Do you mean that the "test2" group gets collapsed inside "test 1"?

Exactly，the trigger condition seems to be to place the collapsed group on the upper edge of the uncollapsed group. In the demonstration, I also placed a card and an uncollapsed group on the upper edge of the test1 group, neither of which were collapsed into the test1 group.
You can also test it yourself to see if the same thing happens.

**Comment by CatCodeMe** [comment]
how to add collapse icon ?

**Comment by Developer-Mike** [comment]
It's available in the latest pre-release.
