### ISSUE TITLE
[FR]Prompt the positional relationship between collapsed groups

### ISSUE THREAD

**Issue by PennHui666** [Developer-Mike/obsidian-advanced-canvas#31]
## Issues Summary
When a group element is collapsed, its original size range is hidden, causing other elements to fall into it when moved. I think it's necessary to create a tip to avoid this happening.

## Suggestions Improvement
- Create cues using grid guides
![image](https://github.com/Developer-Mike/obsidian-advanced-canvas/assets/72249772/8da97919-1a36-40b5-9a92-0e7b1f1de2ef)

- When other elements mistakenly fall into the size range of the collapsed group, the shadow of the range is displayed to serve as a reminder.

**Comment by Developer-Mike** [comment]
Added this feature (but showing all boundaries, not just the ones affected) to the latest release (`2.6.3`).

**Comment by PennHui666** [comment]
Simple and practical border preview, this is amazing.
