### ISSUE TITLE
[FR] Implement A* path style to all edges rather than now, as it can only be done one by one through selection

### ISSUE THREAD

**Issue by smokeSuwen** [Developer-Mike/obsidian-advanced-canvas#33]
The title says it all and I really thank you for creating this plugin. 

Maybe This can be done through one sinlge command or other solution.

I've searched the Obsidian forum and googled, trying to find out how to select all edges or something like that, as that can also fullfill the needs.

Thank you!

**Comment by Developer-Mike** [comment]
I'll add a command to select all edges 👍🏻

**Comment by Developer-Mike** [comment]
This command was added in version `2.6.4`
