### ISSUE TITLE
[BUG]Nested collapsed groups not follow

### ISSUE THREAD

**Issue by PennHui666** [Developer-Mike/obsidian-advanced-canvas#34]
## Issue Summary
The no-follow condition is triggered when the edges of a nested collapsed group extend beyond the edges of the parent collapsed group.
## Screen Recording

https://github.com/Developer-Mike/obsidian-advanced-canvas/assets/72249772/dce2ac15-d86b-40d3-a261-ccb5eb3b82ef

## My Opinion
I'm not sure if this is a bug, but from simple logic, after a collapsed group is fixed to the range of another group, it should become its child node and move accordingly.

**Comment by Developer-Mike** [comment]
This is intentional and exactly like the behavior in the vanilla Obsidian canvas.
