### ISSUE TITLE
[FR] Using cursor postion of click when canvas file node enters edit mode

### ISSUE THREAD

**Issue by longguzzz** [Developer-Mike/obsidian-advanced-canvas#36]
Currently, when a focused file node in canvas is clicked, it only switches into edit mode with the cursor setting to first character of file. Therefore, when editing a file in canvas, user needs to click once to foucs on the node , then click a second time to enter edit mode, and a third time is required to set the cursor position. Reducing the number of operations to one would greatly streamline the process for users who edit multiple files on the canvas heavily.

**Comment by KuiyueRO** [comment]
Do You know this is just a css problem...?

I tried doing it this way, but it didn’t work because the css style gap between ob editor and reading mode is too big.

**Comment by Developer-Mike** [comment]
Sorry for not replying. You can achieve a similar behavior using this CSS snippet.

```css
.canvas-node-content-blocker {
  display: none; /* Or pointer-events: none; */
}
```

But it's not planned to get added to the plugin anytime soon.

**Comment by longguzzz** [comment]
> Do You know this is just a css problem...?
> 
> I tried doing it this way, but it didn’t working great because the css style between ob editor and reading mode is too big.

The CSS snippets in Options > Appearance may help
