### ISSUE TITLE
after installing your app, Obsidian1.5.11 is not able to create canvas file

### ISSUE THREAD

**Issue by josephlam7** [Developer-Mike/obsidian-advanced-canvas#39]

**Comment by Developer-Mike** [comment]
Duplicate of #38

**Comment by josephlam7** [comment]
Not sure how posting a problem in Your GitHub page works, but just to say,
my problem is solved now.
Thank you for you tremendous work in coming out with this wonderful plugin

Joseph

**Comment by Developer-Mike** [comment]
Thank you for your update and your kind words 🙏🏻
