### ISSUE TITLE
[FR]: Add ability to show an alternative cover or text instead of content on canvas

### ISSUE THREAD

**Issue by Lyzod** [Developer-Mike/obsidian-advanced-canvas#43]
Hi Mike, you seem to really wanna make the Canvas a really powerful tool, so I am hoping you might be interested in adding this functionality. 

I ran into that problem that I am overwhelmed with all the text of the notes I am writing and even if I use a card, I would prefer to see eg a picture or another text instead. 

With collapsed notes and css-classes/meta data there is the possibility to define another text or an image with embedd sytax similar to the project plugin, I think. Ofc collapsed notes and not just collapsed notes would be a smaller useful addition that someone else has solved in another plugin already. 

What do you think?

**Comment by Developer-Mike** [comment]
If I understand you correctly, you want collapsible text nodes. I did think about them, but I decided against adding them, because they are not "vanilla" enough.

**Comment by Lyzod** [comment]
I was assuming that a thumbnail view can be best implemented by coupling it with a collapsed view, but if you wanna be more vanilla - which I respect - thumbnails probably also don't fit in your vision. Good that you thought about the collapsed notes, we are all different and have different needs.
