### ISSUE TITLE
[FR] Auto-resize node depending on its content

### ISSUE THREAD

**Issue by KuiyueRO** [Developer-Mike/obsidian-advanced-canvas#45]
I want to be able to auto resize when typing

**Comment by KuiyueRO** [comment]
## For toggle option

[canvas mindmap helper](https://github.com/tim-smart/obsidian-canvas-mindmap) puts this option in the upper right corner.

![image](https://github.com/Developer-Mike/obsidian-advanced-canvas/assets/63145205/2cc2ea54-bc1e-4513-a63f-60e703e1f0a5)

And I suggest that it only takes effect on the node currently in edit mode.

## For width 

### Suggestion 1

`Default node width` as a threshold.

If node width is less than `Default node width`:
- Auto resize width until width = `Default node width`

If the node width is greater than or equal to `Default node width`:
- Do not change width

### Suggestion 2

Don't care about the width, advanced canvas already has a `Default node width`,

If the user changes the width, then this width must be what they want.

**Comment by ramebe2585** [comment]
Auto resize would be great addition! Typically on other canvas software (Logseq, Heptabase, Scapple etc.) the width isn't adjusted when resizing -this solution would work well for my personal workflow, at least. A toggleable setting also sounds ideal.

**Comment by MugenLee** [comment]
yes , I need it

The width can be adjusted manually, because everyone has their own preferences, and the **height can be automatically adjusted according to the content**.

hope it can be implemented as soon as possible. 
This is a very practical function . This can greatly increase the frequency of using canvas as a mindmap.

**Comment by Developer-Mike** [comment]
This got added in version `3.2.0`
