### ISSUE TITLE
[FR] Add more arrow shapes

### ISSUE THREAD

**Issue by Ikaroon** [Developer-Mike/obsidian-advanced-canvas#46]
Hi Mike, I love this plugin and it already gives me a lot to work with. I'm currently trying to plot the class structure for a project in Obsidian and I have the feeling canvas would be great for it. However, there is only one arrow shape as far as I can see.

Do you think it is possible to add more arrow shapes like the ones used in UML diagrams?
![2ajCN](https://github.com/Developer-Mike/obsidian-advanced-canvas/assets/65419234/176bf96b-19b5-474f-921d-aed7a9352db2)

I know there is a UML plugin for Obsidian but it doesn't integrate with Obsidian as neatly as canvas does. With more arrow shapes canvas would be the ideal candidate to become my graph of choice for it.

**Comment by Developer-Mike** [comment]
Look, I could add these arrow shapes pretty easily. But there are some problems. First of all, the users who don't use UML diagrams (and I guess that's a lot of them) would have "clutter" in their user interface. Another problem is the other UML features that are not present in the canvas. For example, the start/end arrow labels and the line-specific arrows. Therefore, the users who use UML are not satisfied either. 

Do you agree with me?

**Comment by Ikaroon** [comment]
I agree that users that use UML can be not satisfied, that's true. I usually don't need the full set of UML features and most developers I know don't use the full set either.
In terms of the "clutter" I can see where you're coming from. I feel like most mindmapping tools out there give at a few more arrow shapes like no-arrow, triangles, diamonds, and circles. But I can see why this isn't part of this plugin.

**Comment by Developer-Mike** [comment]
Good news! In version `3.0.0` (currently pre-release) I've rewritten the styling code. Now, additional styling options won't clutter the popup menu anymore. All requested arrow styles should've been added.
