### ISSUE TITLE
[FR] [bug] button to create a new canvas

### ISSUE THREAD

**Issue by Pixel3ro** [Developer-Mike/obsidian-advanced-canvas#49]
By experimenting. I accidentally found out I could change the file extension at the end of a new note to .canvas and create a new canvas in the current one via Portal. 
But it has some bugs, where it creates an empty card without a "card label" above it. nothing happens upon double clicking it. once you delete this odd-card it unveils the Portal to the newly created canvas. 
This bug occurs sometimes, and sometimes not. 

To avoid this, I create a dummy file and use the Encapsulate feature to create a new Canvas. I would really appreciate a dedicated button to create a new Canvas which is intuitive and helpful. especially with the workflow mentioned in #16

**Comment by Developer-Mike** [comment]
I can't reproduce this behavior... How do you manage to create a canvas file inside a canvas?

**Comment by Pixel3ro** [comment]
> I can't reproduce this behavior... How do you manage to create a canvas file inside a canvas?

i use the "double click to create a new file" feature which was recently added
