### ISSUE TITLE
[minor bug] [minor FR] Collapse-Node compatibility 

### ISSUE THREAD

**Issue by Pixel3ro** [Developer-Mike/obsidian-advanced-canvas#50]
i use this [Collapse-Node](https://github.com/quorafind/obsidian-collapse-node) plugin to fold-unfold cards in my canvas. 
When a Portal is double clicked upon, when it's card is folded, it wont open. 

Collapse-Node is a very handy plugin, and I believe it should be integrated into Advanced Canvas. the plugin is not in active development, and has issues like not recognizing overlapping cards, etc. which leads to a clutter. and the irony is, this plugin's sole job is to help with managing clutter. it'd be a great addition to the suite of tools in Advanced Canvas. Please consider it.

**Comment by Developer-Mike** [comment]
Thank you for your feature request. I already thought about adding collapsible nodes when I was implementing the collapsing groups feature. But I came to the conclusion, that the ability to collapse any node isn't vanilla enough. I hope you understand my decision.
