### ISSUE TITLE
[BUG] A* edges have ugly connections with arrowheads

### ISSUE THREAD

**Issue by MrEbbinghaus** [Developer-Mike/obsidian-advanced-canvas#52]
Arrowheads look weird when using A* edges

![image](https://github.com/Developer-Mike/obsidian-advanced-canvas/assets/2965273/5eef3c0e-5c5c-4bd8-9176-239a3de6d151)

Possible solutions:

## Offset to the target
In the above picture, the target position for A* could be offset slightly to the left, leading to an orthogonal edge into the target. Similarly, the start could be offset if that end has an arrowhead. 

## Rotate the Arrowhead
Pretty self-explanatory. 

## Modify the heuristic
Alternatively, the heuristic could be modified to include a cost penalty based on the distance to a card. 
This could prevent the edge from "sticking" too close to a card if possible, like in this example:

![image](https://github.com/Developer-Mike/obsidian-advanced-canvas/assets/2965273/db4e4c3f-4e19-45ba-8760-5d58b7446077)

**Comment by Developer-Mike** [comment]
Thank you for your bug report (and sorry for not replying 😟). It just got fixed in version `2.7.8`
