### ISSUE TITLE
Can I not change the node shape of actual notes?

### ISSUE THREAD

**Issue by miyamiwu** [Developer-Mike/obsidian-advanced-canvas#53]
The updated pop-up menu with the node shape editor only shows up for cards… Notes that are part of the canvas don’t have the option

**Comment by Developer-Mike** [comment]
This is intended behavior. Can you describe your use case?

**Comment by miyamiwu** [comment]
@Developer-Mike So I’m using Obsidian to worldbuild my novel. Each note is an element in my story. Let’s say I have the notes: God, World, and Magic

In each note, I define what the element is. But in the canvas, I want to show how they are related to each other. If all things start with God, I want the note for god to be oval. God uses Magic to create/power Worlds, so I’d want Magic to be represented as an input, etc.

**Comment by Developer-Mike** [comment]
Can't this better be shown using colors? Because e.g. the circle shape would add a lot of unused, blank space around the text.

**Comment by miyamiwu** [comment]
I already use the colors for something else, such as how each element is related to the protagonist himself..... But yeah, if the node shape for notes can’t be done, it’s fine. I’ll just figure out a different system.
