### ISSUE TITLE
[FR] Node-specific font size

### ISSUE THREAD

**Issue by Eusorph** [Developer-Mike/obsidian-advanced-canvas#55]
It would be great if you could add an option to change font size to a whole card.

**Comment by Developer-Mike** [comment]
How do you imagine the implementation? Should there be a setting in the popup-menu like the settings for the node shapes. Or did you think about something different?

**Comment by Developer-Mike** [comment]
In version `3.0.0` (currently pre-release) you can add custom styling attributes. This is a perfect use case for this new freedom.

**Comment by Developer-Mike** [comment]
Here is a guide to add font size settings:
1. Take a look at the following [instructions](https://github.com/Developer-Mike/obsidian-advanced-canvas?tab=readme-ov-file#custom-styles)
2. Use this snippet for the `data.json` file
```json
 "customNodeStyleAttributes": [
     {
         "datasetKey": "fontSize",
         "label": "Font Size",
         "options": [
             {
                 "icon": "a-arrow-up",
                 "label": "Large",
                 "value": "large"
             },
             {
                 "icon": "a-large-small",
                 "label": "Medium (default)",
                 "value": null
             },
             {
                 "icon": "a-arrow-down",
                 "label": "Small",
                 "value": "small"
             }
         ]   
     }
 ]
```
3. Use this CSS snippet
