### ISSUE TITLE
[FR] an amazing view for card

### ISSUE THREAD

**Issue by CatCodeMe** [Developer-Mike/obsidian-advanced-canvas#57]
hello mike, I find this link in twitter , mayby it can be added to adcanvced-canvas
https://x.com/tone_row_/status/1794736623399440658

**Comment by CatCodeMe** [comment]
I like these features , auto-layout cards  and auto-height of single card , in the twitter

**Comment by Developer-Mike** [comment]
The demo looks cool, but is really hard to implement and for the end user to use efficiently. So I can't imagine this feature being implemented. But an "alternative" could be a "Layout Mode" (#21) so you don't have to position the nodes manually like shown in this demo.
