### ISSUE TITLE
Line and text aliasing artifacts

### ISSUE THREAD

**Issue by AniCator** [Developer-Mike/obsidian-advanced-canvas#59]
Thanks for creation this handy plugin, while I was trying it out I noticed that the lines that are drawn differ in quality compared to the stock Obsidian experience. It appears to affect text as well.
I would guess it has something to do with how everything is transformed.

Here's a comparison, on the left side Advanced Canvas is disabled, on the right side it has been enabled:

![image](https://github.com/Developer-Mike/obsidian-advanced-canvas/assets/2026938/f32d7aa5-32aa-4da3-bdce-0f72c8bb2aef)

The text aliasing becomes a lot less noticeable when you zoom in, but the line aliasing remains.

Here's another two screenshots, the top has the plugin disabled, and the bottom has it enabled:

![image](https://github.com/Developer-Mike/obsidian-advanced-canvas/assets/2026938/83e4e192-42fe-43f6-99e5-07265a8a885d)
(you may have to open the image in a separate tab to see it as it appears the images get scaled down in the issue body)

**Comment by Developer-Mike** [comment]
Thank you for reporting this issue. This is caused by the performance optimization SCSS snippet. I'll change it to an opt-in feature.
