### ISSUE TITLE
Zoom to fit works incorrectly

### ISSUE THREAD

**Issue by dnsflnv** [Developer-Mike/obsidian-advanced-canvas#60]
With the enabled plugin button "Zoom to fit" works as "Default zoom".

To reproduce just try to press that button with the disabled plugin.

**Comment by Developer-Mike** [comment]
I can't reproduce this behavior. But the plugin doesn't modify the "Zoom to fit" button...

**Comment by dnsflnv** [comment]
That's why I'm wondering...

**Comment by Developer-Mike** [comment]
But isn't the default zoom the "fit content zoom"?

**Comment by dnsflnv** [comment]
Not exactly. Behavior without "Advanced canvas":

<img width="666" alt="Screenshot 2024-06-03 at 11 05 21" src="https://github.com/Developer-Mike/obsidian-advanced-canvas/assets/454340/b31f4c5a-c346-4240-b708-a432ebe7402f">

Behavior with "Advanced canvas":

<img width="666" alt="Screenshot 2024-06-03 at 11 04 48" src="https://github.com/Developer-Mike/obsidian-advanced-canvas/assets/454340/dd2bbb4f-5483-4e8e-bc49-57dcc67e6d6e">

Resetting to default zoom, not to fit content.
