### ISSUE TITLE
[FR] Navigation features (Minimap, Zoom and more)

### ISSUE THREAD

**Issue by Pixel3ro** [Developer-Mike/obsidian-advanced-canvas#61]
**>1**: Minimap to navigate ([Example](https://balsamiq.com/assets/wireframes/editor/mini-map.png))

**>2**: Clicking on links take you to the next note
    - When there are multiple links, Hover on link to preview linked notes
    - Support for 'mouse Forward/Backward buttons' - To move between current-previous notes, similar to webpage in a browser
        - if that'd interfere with Obsidian's own support to navigate current page, configuring it to hold-Shift+click, or something similar would help. 
        - Keyboard navigation should be supported as well. perhaps Alt+Left/Right-arrow ?  
    
**>3**: Others
     - Since double-clicking on a note in Canvas automatically zooms into it for visibility, which is handy, there should be an easy way to zoom out as well. like 'Esc' as a keyboard shortcut which takes you to 100% zoom.

**Comment by Developer-Mike** [comment]
1. A minimap isn't vanilla for me. But you can try this plugin: https://github.com/ifree/Obsidian-canvas-minimap (Disclaimer: I've never used it before)
2. Support for keyboard navigation is already planned (#25)
3. This is already natively supported with `Shift + 1`
