### ISSUE TITLE
[FR] Presentation control using PgUp/PgDn

### ISSUE THREAD

**Issue by trungng2006** [Developer-Mike/obsidian-advanced-canvas#62]
Currently, the presentation switch slide with arrow keys.
Could you kindly consider adding pointer as a method for slide switching? 
This capability could help teacher to use obsidian canvas presentation to replace MS Powerpoint.

Thank you

**Comment by trungng2006** [comment]
Actually, i just found out that pointer actually send Page down/page up to switch slide.
Hence, could you add the option to include page down/page up to switch slide?
Thank you!

**Comment by Developer-Mike** [comment]
I probably won't add the ability to switch to the next slide using the pointer click (Or would you still miss this feature despite not being used by the pointer device?). But the PgUp and PgDn can be added 👍🏻

**Comment by trungng2006** [comment]
I think PgUp and PgDn is good (because pointer buttons are mapped to Pgup and PgDn).
Thank you so much!

**Comment by Developer-Mike** [comment]
Just got added in version `2.7.8`

**Comment by trungng2006** [comment]
Thank you!
