### ISSUE TITLE
[FR] Explode .md files to nodes

### ISSUE THREAD

**Issue by Pixel3ro** [Developer-Mike/obsidian-advanced-canvas#65]
Note: I don't want to create a new .md file for every block, like [Cardify](https://github.com/joshuakto/obsidian-cardify) which leads to unnecessary clutter and mismanagement

Imagine you explode a file into multiple cards in a canvas, and they are connected with Lines based on their original flow/structure. 
- Any changes made to these lines will change to the structure in the original file. 
    - an example use case, where you combine multiple .md files. (assume each file gets a unique color of tiles&links) 
       Start by block-explode multiple .md files. link their blocks (maybe with lines of a new color, signifying a new .md file), and club them together creating a new .md file with the said structure. 
       
       a block having more than one link could lead to conflicts. can be solve by a combination of the following
       - a. limiting the number of incoming & outgoing links to 1 per-block. 
       - b. multiple outgoing links get indented under a parent block. (one of them has to be the next block, rather than an indent)
       - c. multiple incoming links - i cannot think of a reasonable structure to handle this. maybe limiting them is the best way to handle this. 

- Support for link embeds in other files. 
    Imagine linking a block with a 'link in the color of a different .md file'. This creates a block-embed. 

- To easily choose different colors(respective .md files) it deserves a panel of sorts to make the UX easy.

**Comment by Developer-Mike** [comment]
Sorry, but this feature is not vanilla at all and a huge amount of work. Thus, there are no plans to implement this.
