### ISSUE TITLE
Question: About disabling presentation

### ISSUE THREAD

**Issue by Pixel3ro** [Developer-Mike/obsidian-advanced-canvas#66]
When I have used Presentation features in some Canvas, and later I disable Presentation in the Plugin options
- what happens to the Presentation config I have created earlier. Will it be lost. Will it create any conflicts if they're still present. 

 
[FR #67 ] is it possible to disable/enable some features per-canvas rather than globally.

**Comment by Developer-Mike** [comment]
The starting node will be saved regardless if the feature is enabled or not. So you can turn on and off the presentation feature as often as you want.
But per-canvas settings won't happen anytime soon (if ever). I'ts just too much work for its usability.
