### ISSUE TITLE
[FR] is it possible to disable/enable some features per-canvas rather than globally.

### ISSUE THREAD

**Issue by Pixel3ro** [Developer-Mike/obsidian-advanced-canvas#67]
related to #66 
I primarily disable the Presentation feature to remove clutter. It may not be a big deal now, but in the future as more tools keep getting added, it might become crucial to manage the icons in popups, etc. 
![Screenshot 2024-06-05 091246|for example](https://github.com/Developer-Mike/obsidian-advanced-canvas/assets/135660353/cb58dfc2-5997-4130-a819-631f9a61a175)

**Comment by Developer-Mike** [comment]
Partially answered in #66. But you're right about the clutter if more tools are getting released. I can assure you, that if it becomes a problem, it will get solved in a way 👍🏻
