### ISSUE TITLE
[FR] XTiles inspired features

### ISSUE THREAD

**Issue by Pixel3ro** [Developer-Mike/obsidian-advanced-canvas#72]
XTiles.app is a Canvas based PKM tool which calls itself a hybrid of miro and notion. it has nice UX which obsidian can borrow. 
this [video ](https://youtu.be/Vegpj1k76HY?t=106 )shows around some of it

i personally like
- drag to create a note
- options to select the type of note - tables, etc. 
- auto align to the top (this does not make sense for the entire canvas)  
    - imagine introducing 'Frames' which are a special type of Group within which cards are auto-aligned
    - The lines of the connected cards might create conflicts with this, as there may not be enough room to display them, or they might lead to unpleasant clutter and confusion if they overlap each-other inconsistently.

**Comment by Developer-Mike** [comment]
I understand why you like this tool. But unfortunately, this is not how Obsidian's canvas works and thus, your suggestions won't be implemented. If you enjoy using XTiles, you can consider switching to it.
