### ISSUE TITLE
[FR] Custom default node/edge style

### ISSUE THREAD

**Issue by aqav** [Developer-Mike/obsidian-advanced-canvas#74]
I have to set the path style to "straight" every time, it there anyway to set default style?

**Comment by Developer-Mike** [comment]
I agree that this would be a cool addition. Unfortunately, canvas can't differentiate if you created a new node or if a new node got created by a file getting loaded (or something getting pasted in). So this feature is unlikely to get implemented.

Feel free to share any ideas how to solve this easily (e.g. a command (with a hotkey) to apply the predefined style).

**Comment by Developer-Mike** [comment]
I've found a way to distinguish them. It got added in version `3.0.0` (currently pre-release)

**Comment by aqav** [comment]
Tks for your excellent work
