### ISSUE TITLE
The arrows are displayed backwards in direct edge path route.

### ISSUE THREAD

**Issue by 1001ruchka** [Developer-Mike/obsidian-advanced-canvas#75]
The arrows are displayed backwards in direct edge path route.

<img width="490" alt="SCR-20240615-lqqe" src="https://github.com/Developer-Mike/obsidian-advanced-canvas/assets/5934321/7fb1ec82-07d6-47b9-86fc-97ebf63b601c">

<img width="513" alt="SCR-20240615-lqvx" src="https://github.com/Developer-Mike/obsidian-advanced-canvas/assets/5934321/0a17f7f9-8c8f-491e-8e7c-5f646403466d">

Other edge path route do not have this problem.

<img width="533" alt="SCR-20240615-lrbu" src="https://github.com/Developer-Mike/obsidian-advanced-canvas/assets/5934321/787caa36-5ad6-4c2c-b10d-ba0c2ea331c4">

<img width="474" alt="SCR-20240615-lrgq" src="https://github.com/Developer-Mike/obsidian-advanced-canvas/assets/5934321/74e92625-4d2b-48bf-bf6f-6654e6830d4d">

**Comment by 1001ruchka** [comment]
I took a closer look. The arrows are not displayed backwards, they are simply not parallel to the line, and since the arrow is triangular there is an illusion that it is directed in the opposite direction.
For straight lines, the direction of the arrow must be parallel to the route line.

<img width="497" alt="SCR-20240615-mdll" src="https://github.com/Developer-Mike/obsidian-advanced-canvas/assets/5934321/81abd194-de72-4728-8514-f2b607d6cf26">

**Comment by 1001ruchka** [comment]
In the plugin https://github.com/michaellw/Obsidian-Canvas-Style-Menu the arrow part of the code is implemented as follows:

```
 if (propertyValue === "cs-line-straight") {
                  const displayPath = this.lineGroupEl.querySelector(".canvas-display-path");
                  const interactionPath = this.lineGroupEl.querySelector(".canvas-interaction-path");
                  displayPath.setAttribute("d", linePath);
                  interactionPath.setAttribute("d", linePath);
                  if (this.toLineEnd && !this.fromLineEnd) {
                    const toNewTransform = this.toLineEnd.el.style.transform.replace(/rotate\([-\d]+deg\)/, `rotate(${toRotateAngle}deg)`);
                    this.toLineEnd.el.style.transform = toNewTransform;
                  }
                  if (this.fromLineEnd) {
                    const fromNewTransform = this.fromLineEnd.el.style.transform.replace(/rotate\([-\d]+deg\)/, `rotate(${fromRotateAngle}deg)`);
                    const toNewTransform = this.toLineEnd.el.style.transform.replace(/rotate\([-\d]+deg\)/, `rotate(${toRotateAngle}deg)`);
                    this.fromLineEnd.el.style.transform = fromNewTransform;
                    this.toLineEnd.el.style.transform = toNewTransform;
                  }
                }
```

**Comment by Developer-Mike** [comment]
Added an option to rotate the arrows in version `3.0.0` (currently pre-release)
