### ISSUE TITLE
[bug] Shape > Predefinded Process doesn't seems to be applied on the canvas object

### ISSUE THREAD

**Issue by danieltomasz** [Developer-Mike/obsidian-advanced-canvas#76]
Shape > Predefinded Process doesn't seems to be applied on the canvas object, all other shapes that are choosen seem to have an effect.
Obsidian 1.6.5,Plugin version 3.0.1

**Comment by Developer-Mike** [comment]
Looks like I was pretty drunk while coding 😅 (https://github.com/Developer-Mike/obsidian-advanced-canvas/blob/main/src%2Fstyles%2Fnode-styles.scss#L117). Will be fixed today.

**Comment by Developer-Mike** [comment]
This bug was fixed in version `3.0.2`
