### ISSUE TITLE
Properties button missing from menu?

### ISSUE THREAD

**Issue by mercury19** [Developer-Mike/obsidian-advanced-canvas#77]
I'm trying to style some group titles on a particular canvas and I have the css snippets working, but I can't apply them to a specific class because the "properties button" on the little side menu isn't there for some reason? I'm currently working on Windows, but I've noticed on Android sometimes it is there and sometimes it isn't. Is this a bug or maybe a conflict of some kind?

**Comment by mercury19** [comment]
Nevermind I restarted the app and it was there again

**Comment by Developer-Mike** [comment]
Make sure you always restart Obsidian after an update or a fresh installation. If not, some bugs may occur.
