### ISSUE TITLE
No Edge Styles button

### ISSUE THREAD

**Issue by Marco-Mindstone** [Developer-Mike/obsidian-advanced-canvas#8]
Hi, the "Edge Styles" button is not showing up.

<img width="613" alt="image" src="https://github.com/Developer-Mike/obsidian-advanced-canvas/assets/112725579/3b14e2f4-8da0-42e0-82ed-bec630443e5a">

**Comment by Developer-Mike** [comment]
I'm sorry for the confusion. This feature is still unreleased. If you want to use it now, you need to build the plugin by yourself (`npm run dev`). I will add a notice in the future if something isn't released yet.

**Comment by Developer-Mike** [comment]
Added in release [2.4.0](https://github.com/Developer-Mike/obsidian-advanced-canvas/releases/tag/2.4.0)
