### ISSUE TITLE
Centered text alignment not maintained during node size change

### ISSUE THREAD

**Issue by DrRerio** [Developer-Mike/obsidian-advanced-canvas#84]
I would like to use centered text on my nodes (Ex1), but when I try to resize the node (decrease width) to have text on multiple lines, the centered alignment is lost (Ex2). 

**Ex1**
![Ex1](https://github.com/Developer-Mike/obsidian-advanced-canvas/assets/106784135/1403dcb0-7009-4912-9b53-7a4c2a21e4f5)

**Ex2**
![Ex2](https://github.com/Developer-Mike/obsidian-advanced-canvas/assets/106784135/ca7764d0-7678-4c9f-8d22-1efece657523)

I've noticed that you can get around this by adding a 'new line' (Ex3), but this can be a bit of a hassle when making these changes across multiple nodes.

**Ex3**
![Ex3](https://github.com/Developer-Mike/obsidian-advanced-canvas/assets/106784135/7ac040ab-a86f-484b-b901-293a0b5f1a4b)

Additionally, if left/right alignment is used, the text loses its vertically centered alignment (Ex4).

**Ex4**
![Ex4](https://github.com/Developer-Mike/obsidian-advanced-canvas/assets/106784135/d3ab57e7-f93a-4c28-9d33-680d9ab565fb)

Lastly, text often continues out of view when using certain shapes (eg. diamond & circle). It would be great if the text in these shapes was restricted within the shape boundaries and auto-fit while resizing as it does with other shapes.

**Comment by Developer-Mike** [comment]
Thank you for your bug report. The centering of the text will be fixed in the next version. But restricting the text to flow in the shape seems too difficult to achieve. I might revisit this at a later date.

**Comment by Developer-Mike** [comment]
Ex1 and Ex2 got fixed in version `3.0.4`. And Ex3 is intentional. If you want to change this behavior, consider adding custom style attributes (https://github.com/Developer-Mike/obsidian-advanced-canvas?tab=readme-ov-file#custom-styles)

**Comment by DrRerio** [comment]
Thanks so much, Mike!
