### ISSUE TITLE
[FR]  Auto-Append "Canvas Name" to New Markdown Files

### ISSUE THREAD

**Issue by Pixel3ro** [Developer-Mike/obsidian-advanced-canvas#85]
**Example Use Case:**
Consider an example where you have a canvas named _"ApplePieRecipe.canvas"_. When creating new markdown files within this canvas, one might use short names such as _"ingredients.md" "steps-to-follow.md" etc._ 
However, when searching through the entire Obsidian vault, files such as "ingredients.md" would have counterparts in other recipe canvases. Because these file-names lack sufficient context, it becomes _**difficult to distinguish between multiple files with the same name**_.

**Feature:** **_Auto-Append ParentCanvasName to new .md files created within Canvas_**
If a new markdown file is created within a canvas named _"ApplePieRecipe.canvas"_, the file name will be **automatically** set to _"NewFileName - ApplePieRecipe.md"_. 
_Appending the ParentCanvasName_ to the file name _provides necessary context_, making it _easier to navigate while searching_ for files in a large Vault.
This feature is intuitive to adopt many common use cases, like _"todo.md", "log.md"_ created in any _Project-canvas_. 

**Considerations:** - _describing the finer details_
1. **Default Behavior of Auto-Append**
**Importing existing files** - In most use-cases adding CanvasContext to a File which is made elsewhere would lead to confusions. _Eg. DailyNotes.md, grocery_list.md_ So **_Auto-Append is disabled for imported files by default_**. 
**Only newly created files** within a Canvas are Auto-Appended with the name of the ParentCanvas. 
2. **On/Off - _Per-Canvas_:** There should be a way to allow the user to manually enable/disable Auto-Append feature to _individual Canvases_. _**Note:**_ This configuration is retained even after an app restart. 
3. **On/Off - _Canvas(Global)_:** In _plugin options_, a toggle called _"Global Default"_ decides if Auto-Append is enabled/disabled for _All-the-Canvases_ in the Vault. **_Note:_** Toggling this back and forth should _NOT_ affect manual configs made in `pt.2` 
4. **On/Off - _Files_:** add/remove CanvasContext to individual FileNames
   - **For singe files** - A _button_ to "add/remove" the selected file's CanvasContext. **_Note1:_** The current state of CanvasContext of the file _(obtained by checking the FileName if CanvasContext is already appended or not)_ is indicated via [button state](https://miro.medium.com/v2/resize:fit:1028/1*6jheh_d54hXl6q5V2vlkSQ.png). This helps the interaction intuitive. **_Note2:_** users editing the file-name directly to _manually-modify CanvasContext_ should be recognized and not cause bugs/conflicts. 
   - **For multiple files** - Upon _Multi-selecting_ files in Canvas and a button to **bulk-add/remove** CanvasContext  
5. **On/Off - _while creating a new file_: ** 
While adding files to the Canvas by typing the name of a file, **Enter-key** would import an existing file from the search results dropdown, **Shift+Enter** would create a new file. Similarly a shortcut **_/+Enter_ for example** could give finer control over Auto-Append while creating a new file. 
- if Auto-Append is **enabled _(Per-Canvas/Global)_** - **_shortcut_ Disables** it _only for the currently created file_. 
- if Auto-Append is **disabled _(Per-Canvas/Global)_** - **_shortcut_ Enables** it _only for the currently created file_. 
6. Auto-Append to include **GroupName** formatted as _"FileName - GroupName - ParentCanvasName.md"_
7. For users who use _Portal feature (Canvas-Embeds)_ similar **Auto-Append features for Canvases** that are _newly created_ within the _CurrentCanvas_ would be useful. [ I add _.canvas_ at the end of FileName **_to create EmbeddedCanvas_** within currentCanvas  Eg. _Kindle_Highlights.canvas_] 
8. An API or similar functionality to allow the "Canvas-File relationship" to be used by other tools like Templater, where one can add {ParentCanvasName} to YAML metadata, etc. (I understand this could be overkill. I am only describing how I had imagined the bigger picture without cutting short. I totally understand if some of these features are to be ignored for the time being. personally I think _pts. 5, 7, 8_ can be ignored if need be)

**Comment by Developer-Mike** [comment]
1-7: While I do understand your particular use case, I've personally never missed a feature like this one. And considering the effort needed to implement such a feature and regarding the other planned features, this feature is at the bottom of the priority list.
8: This could be added for #16

Due to those circumstances, I'll close this issue as not planned for now.
