### ISSUE TITLE
Change the edge colour separately from the fill colour

### ISSUE THREAD

**Issue by 1001ruchka** [Developer-Mike/obsidian-advanced-canvas#89]
I would like to be able to change the edge colour separately from the fill colour. 
So I can make red edges and green fill for example.

<img width="262" alt="image" src="https://github.com/user-attachments/assets/ff60e925-5155-44f3-82a1-0158098b6a26">

**Comment by Developer-Mike** [comment]
This is not planned but easily achievable using a custom style (https://github.com/Developer-Mike/obsidian-advanced-canvas?tab=readme-ov-file#custom-styles). You could add an attribute named "Fill Color" for example.
