### ISSUE TITLE
please add mind map on canvas

### ISSUE THREAD

**Issue by Andry042023** [Developer-Mike/obsidian-advanced-canvas#90]
please add mind map on canvas
![image](https://github.com/user-attachments/assets/7013f463-d7e3-431d-a1ec-1addba01993a)

**Comment by Andry042023** [comment]
![image](https://github.com/user-attachments/assets/3b6e12af-2e13-4672-8559-5d852a0dd9b5)

**Comment by Developer-Mike** [comment]
Predefined layouts are planned (#21) and you can easily achieve this look by coloring the arrows and changing the node border to invisible.

**Comment by Andry042023** [comment]
thank you a lot)
