### ISSUE TITLE
focus mode

### ISSUE THREAD

**Issue by Andry042023** [Developer-Mike/obsidian-advanced-canvas#91]
it would be great to have a focus mode when we click on one card, the others become less bright. Is it possible to implement this?

![image](https://github.com/user-attachments/assets/fdbc14b0-8a71-4323-a234-255b90e6c758)

**Comment by Developer-Mike** [comment]
Thank you for this suggestion. It will get added 👍🏻

**Comment by Developer-Mike** [comment]
A focus mode got added in version `3.1.0`
