### ISSUE TITLE
Font of group name and arrow text does not zoom with canvas

### ISSUE THREAD

**Issue by SdKay** [Developer-Mike/obsidian-advanced-canvas#99]
Thanks for the excellent plugin!!
I found that font of group name and arrow does not zoom with canvas. Is this intentional? When I zoom out, the text keep same view size and may overlap the graph. 

![image](https://github.com/user-attachments/assets/08f466b7-2776-48df-9f97-f25296de9945)

room out: 

![image](https://github.com/user-attachments/assets/7f2ed43a-2cd1-489f-92af-d0dc84786d2c)

**Comment by Developer-Mike** [comment]
This is the default behaviour of the inbuilt canvas plugin. Would you like to make a feature request to disable this automatic scaling?

**Comment by SdKay** [comment]
Emm, Dont konw how to make a feature request 🤣, Do I need to find the solution how to diable it?

**Comment by SdKay** [comment]
> This is the default behaviour of the inbuilt canvas plugin. Would you like to make a feature request to disable this automatic scaling?

Emm, Dont konw how to make a feature request 🤣, Do I need to find the solution how to diable it?

**Comment by Developer-Mike** [comment]
No 😅. You just need to tell me that you want it as a feature. I wasn't quite sure if this is a "bug" report or a feature request. I rather make sure you want this feature than waste time on a feature you didn't even want.

**Comment by SdKay** [comment]
OK, Here is the detail:

### Problem
Font of group name and arrow text does not zoom with canvas while keeping fixed preview font size.

Here is in detail view, everyting is ok, no hidden or overlap items:
![image](https://github.com/user-attachments/assets/7c1c2ca8-a226-4fb2-b6f7-39758f2b5f19)

But when I zoom out and just want to see the structure and not focus on the detail. Then group name is hidden partially and the text on arrow overlap the node which is ugly and bad for reading
![image](https://github.com/user-attachments/assets/2954e21b-ecf0-4709-9d51-546ffb458f53)


### Request
1. Keep Group name font size **zoom with canvas**. The font size can be larger than text of Node and **never be hidden**.
2. Keep arrow text font size **zoom with canvas**. It's better if the **text style can be customized** (becase arrow text usually is an important notice)

**Comment by Developer-Mike** [comment]
This feature will be available in version `3.1.1`
